---
title: "Volleyball Project (7960)"
output: html_document
date: "2024-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r}
library(dplyr) # Data Manipulation Package %>% 
library(tidyr) # Data Cleaning Package
library(readxl) # Excel
library(tidyverse) # Cleaning/Manipulating
library(purrr) # Initializing Lists to Data Frames
library(lubridate) # Working with Dates
library(openxlsx) # Excel 
library(stringr) # String Splitting
library(ggplot2) # Plotting
library(stringr) # Prefix/Suffix Editing
library(manipulate) # Easy Chart Manipulation
library(stargazer) # Regression Formatter
```

# Initializing Data Frames
```{r}
setwd("C:/Users/spike/Box/AHPS Projects/AHPS Volleyball Project/")

# Force Plate Data Frame
forceplate_df <- read_excel("VB DJ Data/VB Drop Jump All Metrics.xlsx")

# Catapult Data
catapult_df <- read.csv("Catapult/VB_Catapult_By_Position_ver2.csv")

# Gameday Data
team_match_stats <- read_excel("Exported Files/teams_match_stats.xlsx")
player_match_stats <- read.csv("Exported Files/Player_Match_Stats.csv")
```

## Simple Linear Regression on Wins
```{r}

# Select Just Utah Match Stats
utah_match_stats <- team_match_stats %>% 
  filter(Player_Name == "University of Utah")

utah_match_stats <- utah_match_stats %>% 
  mutate(Win_Dummy = ifelse(Game_Outcome == "Win", 1, 0))

  
basic_model <- lm(Win_Dummy ~ Attacking_K_Perc, data = utah_match_stats)


summary(basic_model)


colnames(utah_match_stats)
```

## Setting up data frame for Stan
```{r}
# Run above Code Chunk for rest of utah_match_stats formatting
# Select Columns I want to Analyze for just Utah
utah_stan_df <- utah_match_stats %>% 
  select(Player_Name, Attacking_Kills, Attacking_K_Perc, Attacking_E_Perc, Attacking_Efficiency, 
         Defense_D_Perc, Serving_E_Perc, Serving_A_Perc, Game_Score, 
         Game_Outcome, Score_Differential, Win_Dummy, Date_of_Game) %>% 
  rename(Team = Player_Name)


# Select Columns to get a differential of between teams
teams_stan_df <- team_match_stats %>% 
  select(Player_Name, Attacking_Kills, Attacking_K_Perc, Attacking_E_Perc, Attacking_Efficiency, 
         Defense_D_Perc, Serving_E_Perc, Serving_A_Perc ,Game_Score, 
         Game_Outcome, Score_Differential, Date_of_Game, Opponent) %>% 
  rename(Team = Player_Name) %>% 
  mutate(Win_Dummy = ifelse(Game_Outcome == "Win", 1, 0))

cols_to_multiply <- c("Attacking_K_Perc", "Attacking_E_Perc", "Defense_D_Perc", "Serving_E_Perc", "Serving_A_Perc", "Attacking_Efficiency")

utah_stan_df <- utah_stan_df %>% 
  mutate_at(vars(cols_to_multiply), ~ . * 100)

teams_stan_df <- teams_stan_df %>% 
  mutate_at(vars(cols_to_multiply), ~ . * 100)

# Function to Calculate Differences between teams
calculate_differences <- function(data, columns) {
  result_df <- data.frame(Team = character(),
                          Opponent = character())
  
  for (i in seq(1, nrow(data), by = 2)) {
    temp_diff <- data.frame(
      Team = paste0(data$Team[i]),
      Opponent = data$Opponent[i],
      Outcome = data$Game_Outcome[i],
      Win_Dummy = data$Win_Dummy[i],
      Score_Differential = data$Score_Differential[i],
      Date = data$Date_of_Game[i],
      sapply(columns, function(col) {
        data[i, col] - data[i + 1, col]
      })
    )
    
    result_df <- bind_rows(result_df, temp_diff)
  }
  
  return(result_df)
}

columns_to_difference <-  c("Attacking_Kills", "Attacking_K_Perc", "Attacking_Efficiency", 
                            "Defense_D_Perc", "Serving_E_Perc", "Serving_A_Perc")

# Run Function
diff_stan_df <- calculate_differences(teams_stan_df, columns_to_difference)

# Rename Correctly
diff_stan_df <- diff_stan_df %>% 
  rename(
      Attacking_Kills = "Attacking_Kills.Attacking_Kills",
      Attacking_Efficiency = "Attacking_Efficiency.Attacking_Efficiency",
      Attacking_K_Perc = "Attacking_K_Perc.Attacking_K_Perc",
      Defense_D_Perc = "Defense_D_Perc.Defense_D_Perc",
      Serving_A_Perc = "Serving_A_Perc.Serving_A_Perc",
      Serving_E_Perc = "Serving_E_Perc.Serving_E_Perc",
  )



# Plotting the relationship
ggplot(utah_stan_df, aes(x = Attacking_K_Perc, y = Win_Dummy)) +
  geom_point()

ggplot(diff_stan_df, aes(x = Attacking_K_Perc, y = Win_Dummy)) +
  geom_point() 



# Set up Catapult Data frames
catapult_df <- catapult_df %>% 
  filter(Position.Name != "Libero")

catapult_df$Date <- as.Date(catapult_df$Date, format = "%m/%d/%Y")


# Combine High Jumps for all and Medium Jumps for Setters
catapult_df <- catapult_df %>%
  group_by(Date) %>%
  mutate(Good_Jumps = sum(ifelse(Position.Name == "Setter", Avg_Jump_Count_Medium, Avg_Jump_Count_High)))

catapult_df <- catapult_df %>%
  group_by(Date) %>%
  mutate(Total_Jumps = sum(Avg_Total_Jump_Count))

catapult_df <- catapult_df %>%
  group_by(Date) %>%
  mutate(Perc_Good_Jumps = (Good_Jumps / Total_Jumps) * 100)




# Set up other 2 data frames
gameday_catapult <- catapult_df %>% 
  filter(GD_Indicator == "GD")

# Selects only one observation per date
gameday_catapult <- gameday_catapult %>%
  select(Date, Perc_Good_Jumps) %>%
  distinct() 

# Select Gameday dates and Kill % (For Differentials)
diff_kill_gameday <- diff_stan_df %>% 
  select(Date, Attacking_K_Perc)

# Merge Them
gameday_catapult <- merge(gameday_catapult, diff_kill_gameday, by = "Date", all = FALSE)

gameday_catapult <- gameday_catapult %>%
  select(-Date)


# Filter
changed_gamedays <- catapult_df %>% 
  mutate(GD_Indicator = ifelse(Date == as.Date("2023-08-25") | Date == as.Date("2023-09-08"), "GD-1", GD_Indicator))

gd_neg_1_catapult <- changed_gamedays %>% 
  filter(GD_Indicator == "GD-1")

# Make Player Load Average by Date
gd_neg_1_catapult <- gd_neg_1_catapult %>% 
  group_by(Date) %>% 
  mutate(Player_Load_Per_Min = mean(Avg_Player_Load_Per_Min))

# Alternate Date
gd_neg_1_catapult <- gd_neg_1_catapult %>% 
  mutate(NearestGameday = Date + 1)

# Select one per date
gd_neg_1_catapult <- gd_neg_1_catapult %>% 
  select(Date, NearestGameday, Player_Load_Per_Min, Perc_Good_Jumps) %>% 
  distinct()

gd_neg_1_catapult <- gd_neg_1_catapult %>% 
  rename(Practice_Date = Date) %>% 
  rename(Date = NearestGameday)

# Merge the data frames
gd1_catapult <- merge(gd_neg_1_catapult, diff_kill_gameday, by = "Date", all = FALSE)

# Remove Unneeded Column
gd1_catapult <- gd1_catapult %>% 
  select(-Practice_Date) %>% 
  select(-Date)


```

